Notifications: Notifications
UserSettings: User settings
Settings: Settings
NoDefaultRingtonesSetYet: Default ringtones have not yet been set
DefaultRingtone: Default ringtone
IncomingChatMessage: Incoming chat message
OutgoingChatMessage: Outgoing chat message
DefaultSettings: Default settings
AlreadyExists: Already exists
SelectNewRingtoneFile: Select new ringtone file
SelectRingtoneFile: Select ringtone file
RingtoneNotFound: Ringtone not found
Type: Type
RecordAdded: Record added
NoFileChosen: No file chosen
SelectRingtone: Select ringtone
UploadRingtone: Upload ringtone
Default: Default
Name: Name
TheName: Name
NoRingtonesYet: No ringtones yet
Ringtone: Ringtone
Ringtones: Ringtones
Unselected: Unselected
Selected: Selected
YouAreTryingToCallYourself: You're trying to call yourself
CancelThisSubscription: Cancel this subscription
UserSubscribedOnThisDevice user@Text: #{user} is subscribed on this device
CallerCalleeSubscriptionLoopWarning: It seems that the callee is also subscribed on this device
UserYouSeemsUnsubscribed user@Text: #{user} (you) seems unsubscribed
UserAppearsToBeUnavailable user@Text: #{user} appears to be unavailable
UserAgent: User agent
Endpoint: Endpoint
Subscription: Subscription
TheUserSubscriptions: User Subscriptions
NoSubscriptionsYet: No subscriptions yet
Subscriptions: Subscriptions
WebRealTimeCommunication: Web Real-Time Communication
Configuration: Configuration
Answer: Answer
NewMessageFrom user@Text: New message from Julian
UserIsNowAvailable user@Text: #{user} is now available
RefreshPage: Refresh page
Refresh: Refresh
EntityCall: Call
CallCanceled: Call canceled
SelectCalleeToCall: Select a callee from the list to call
YouHaveNotMadeAnyCallsYet: You haven't made any calls yet
Chats: Chats
Calls: Calls
EntityChat: Chat
PushSubscription: Push subscription
BasicEntities: Basic Entities
Overview: Overview
YouAreNotSubscribedToNotificationsFrom user@Text: You are not subscribed to notifications from user #{user}
YouAreNotYetInContactListOfUser user@Text: You are not yet in the contact list of user #{user}
AllowToBeNotifiedBy user@Text: Allow user #{user} to send you notifications about incoming calls
Usage: Usage
AuthenticationRequired: Authentication required
AuthorizationRequired: Authorization required
IncomingVideoCallFrom caller@Text: Incoming video call from #{caller}
IncomingAudioCallFrom caller@Text: Incoming audio call from #{caller}
CallCanceledByCaller caller@Text: Call canceled by #{caller}
SendMessagesVideochatOrAudioCall: Send messages, video chat or make audio calls
MyContacts: My contacts
YouMightWantToAddAFew: You might want to add a few
YourContactListIsEmpty: Your contact list is empty
ShowMyContacts: Show my contacts
LogIn: Log in
LoginToAccessYourContacts: Login to access your contacts
WelcomeTo: Welcome to
ClientSecret: Client secret
ClientId: Client id
SearchEngineOptimization: Search Engine Optimization
Username: Username
IssueTracking: Issue tracking
InterlocutorStartedSession interlocutor@Text: #{interlocutor} started the session
InterlocutorEndedSession interlocutor@Text: #{interlocutor} has ended the session
EndSession: End session
Allow: Allow
Subscribe: Subscribe
NotNow: Not now
AllowToBeNotified: Allow to be notified about incoming video calls, audio calls and messages
FailedToCancelSubscription: Failed to cancel subscription
SubscriptionCanceled: Subscription canceled
SubscriptionFailed: Subscription failed
SubscriptionSucceeded: Subscription succeeded
RemoveAreYouSure: Are you sure you want to remove?
Remove: Remove
CalleeDeclinedTheCall callee@Text: #{callee} declined the call 
CallDeclined: Call declined
IncomingAudioCall: Incoming audio call
IncomingVideoCall: Incoming video call
Decline: Decline
Accept: Accept
MissedCall: Missed call
Close: Close
VideoSession: Video Session
CallEnded: Call ended
IncomingCall: Incoming call
OutgoingCall: Outgoing call
AudioCall: Audio call
VideoCall: Video call
Audio: Audio
Video: Video
ContactList: Contact list
TextChat: Chat via text message
NewMessage: New message
Notification: Notification
Ignore: Ignore
Reply: Reply
PushNotificationExcception: Push notification error
NoMessagesExchangedYet: No messages exchanged yet
SubscribeToNotifications: Subscribe to notifications
NotGeneratedVAPID: VAPID not generated
ErDiagram: ER Diagram
Contact: Contact
Actions: Actions
ViewContact: View contact
NewContactsAdded: New contacts added
AddSelected: Add selected
AddContacts: Add contacts
Select: Select
NoRegisteredUsersYet: There are no registered users yet
Add: Add
NoContactsYet: There are no contacts yet
Message: Message
LoginToViewContacts: Log in to view contacts
Contacts: Contacts
GmailAccountNotSet: Gmail account is not set. Initialize tokens.
ThankYou: Thank you
ConfirmEmailPlease: Please confirm your email address by clicking on the link below
VerifyYourEmailAddress: Verify your email address
Administrator: Administrator
Superuser: Superuser
Photo: Photo
DemoUserAccounts: Demo user accounts
Password: Password
EmailAddress: Email address
CreateAccount: Create account
DoNotHaveAnAccount: Don't have an account?
SignIn: Sign in
ForgotYourPassword: Forgot your password?
Or: or
Registration: Registration
Back: Back
ResendEmail: Resend email
DidNotGetEmail: Didn't receive the email?
ClickToVerifyAccount: Click the link in the email to verify your account
JustSentEmailTo: We just sent an email to
VerifyEmailPlease: Please verify your email
EmailVerification: Email verification
CreatePassword: Create password
PasswordRecovery: Password recovery
SignInWithGoogle: Sign in with Google
PageNotFound: Page not found
PermissionDenied: Permission denied
InvalidArguments: Invalid arguments
BackToHomepage: Go back to homepage
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
Welcome: Welcome
Tokens: Tokens
MainMenu: Main menu
Data: Data
Users: Users
Documentation: Documentation
SourceCode: Source code
Resources: Resources
AppDocumentation: App documentation
NoUsersYet: There are no users yet
SignOut: Sign out
UserAccount: User account
User: User
Save: Save
Cancel: Cancel
Yes: Yes
VerificationKey: Verification key
Verified: Verified
No: No
FullName: Full name
Google: Google
Email: Email
Edit: Edit
Dele: Delete
ConfirmPlease: Please confirm
DeleteAreYouSure: Are you sure you want to delete?
InvalidFormData: Invalid form data
RecordDeleted: Record deleted
NotSpecified: Not specified
RecordEdited: Record edited
SuperuserCannotBeDeleted: Superuser cannot be deleted
Attribution: Attribution
AnotherAccountAccessProhibited: Access to another user's account is prohibited
PersonalInfo: Personal info
Account: Account
Birthday: Birthday
NotIndicated: Not indicated
Initialize: Initialize
UserSession: User session
Database: Database
StoreType: Store type
InvalidStoreType: Invalid store type
ClearSettings: Clear
Cleared: Cleared
GmailAccount: Gmail account
GoogleSecretManager: Google Secret Manager
Generate: Generate
VapidGenerationWarning: Generating a new VAPID key requires all clients to re-subscribe to the push notifications
InvalidGoogleAPITokens: Invalid Google API tokens
AppDescription: Instant Messaging and Video Calling
AppName: Videre
MetaKeywords: instant, messaging, progressive, web, app, pwa
MetaDescription: Progressive Web App for Instant Messaging and Video Calling

Doc001 appname@Text href1@Text href2@Text href3@Text href4@Text: Application <a href=#{href1} target=_blank>#{appname}</a> allows users to exchange instant messages via <a href=#{href2} target=_blank>WebSockets</a>, make audio and video calls via <a href=#{href3} target=_blank>WebRTC</a>, and be notified via <a href=#{href4} target=_blank>Web Push</a>.

Doc002: A superuser account is defined at deployment time. The superuser manages other users and grants or revokes administrator privileges to specific users.

Doc003: Integration with external APIs

Doc004 href@Text: <a href=#{href} target=_blank>Project repository</a> on GitHub.

Doc005 href@Text: Please note that the application currently running is a demo application. Any actions are allowed and encouraged. <a href=#{href} target=_blank>Report issues</a> on GitHub.

Doc006 href@Text: To call each other, users must <a href=#{href} target=_blank>register</a> in the application and add each other to their contact list from among registered users.

Doc007: When adding a user to your contacts list, the app will ask for permission to send notifications and subscribe to the push notification service.

Doc008: The app uses the browser's push notification service to notify the callee of an incoming video or audio call.

Doc009 href@Text: By accepting the call, a peer-to-peer encrypted video/audio session will start between the caller and the callee as described by the <a href=#{href} target=_blank>WebRTC protocol</a>.

Doc010 href1@Text href2@Text: A new user can <a href=#{href1} target=_blank>sign up</a> using an existing Google account or using a verified email address. <a href=#{href2} target=_blank>Gmail API</a> is used as an intermediary to send verification links to the user's inbox.

Doc011: A user can be grated the administrator role by a superuser or by another administrator. Only users with the administrator role have access to administrative data.

Doc012: A contact is created when a user adds another user to their contact list. If each user has each other in their contact list, then they can call each other.

Doc013: A push subscription is created when the user is added to the contact list, or it can be deferred until later.

Doc014: The subscription can be checked or renewed from the “View contact” menu item.

Doc015 href@Text: <a href=#{href} target=_blank>Web Push Notifications</a> are used to notify a callee of an incoming video/audio call. It is also used to end the video/audio session.

Doc016: The entity Call represents outgoing and incoming calls to the currently logged in user.

Doc017 link@Text: The configuration can be provided as a textual representation of a JSON object as described in <a href=#{link} target=_blank>RTCPeerConnection() constructor</a>.

Doc018: Mainly used to specify STUN and TURN servers.

Doc019: The Chat entity represents messages exchanged between two users. By default, chat messages are exchanged and stored using the WebSockets protocol. Peer-to-peer messaging without intermediate storage is planned for future releases.

Doc020 link@Text: New ringtones can be added by an administrator in the <a href=#{link} target=_blank>"Ringtones"</a> section of the "Data" menu.

Doc021: An administrator can also set default ringtones for each call type, outgoing or incoming call.