GmailAccountNotSet: Gmail account is not set. Initialize tokens.
ThankYou: Thank you
ConfirmEmailPlease: Please confirm your email address by clicking on the link below
VerifyYourEmailAddress: Verify your email address
Administrator: Administrator
Superuser: Superuser
Photo: Photo
DemoUserAccounts: Demo user accounts
Password: Password
EmailAddress: Email address
CreateAccount: Create account
DoNotHaveAnAccount: Don't have an account?
SignIn: Sign in
ForgotYourPassword: Forgot your password?
Or: or
Registration: Registration
Back: Back
ResendEmail: Resend email
DidNotGetEmail: Didn't receive the email?
ClickToVerifyAccount: Click the link in the email to verify your account
JustSentEmailTo: We just sent an email to
VerifyEmailPlease: Please verify your email
EmailVerification: Email verification
CreatePassword: Create password
PasswordRecovery: Password recovery
SignInWithGoogle: Sign in with Google
PageNotFound: Page not found
PermissionDenied: Permission denied
InvalidArguments: Invalid arguments
BackToHomepage: Go back to homepage
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication