LoginToViewContacts: Log in to view contacts
Contacts: Contacts
GmailAccountNotSet: Gmail account is not set. Initialize tokens.
ThankYou: Thank you
ConfirmEmailPlease: Please confirm your email address by clicking on the link below
VerifyYourEmailAddress: Verify your email address
Administrator: Administrator
Superuser: Superuser
Photo: Photo
DemoUserAccounts: Demo user accounts
Password: Password
EmailAddress: Email address
CreateAccount: Create account
DoNotHaveAnAccount: Don't have an account?
SignIn: Sign in
ForgotYourPassword: Forgot your password?
Or: or
Registration: Registration
Back: Back
ResendEmail: Resend email
DidNotGetEmail: Didn't receive the email?
ClickToVerifyAccount: Click the link in the email to verify your account
JustSentEmailTo: We just sent an email to
VerifyEmailPlease: Please verify your email
EmailVerification: Email verification
CreatePassword: Create password
PasswordRecovery: Password recovery
SignInWithGoogle: Sign in with Google
PageNotFound: Page not found
PermissionDenied: Permission denied
InvalidArguments: Invalid arguments
BackToHomepage: Go back to homepage
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
Welcome: Welcome
Tokens: Tokens
MainMenu: Main menu
Data: Data
Users: Users
Documentation: Documentation
SourceCode: Source code
Resources: Resources
AppDocumentation: App documentation
NoUsersYet: There are no users yet
SignOut: Sign out
UserAccount: User account
User: User
Save: Save
Cancel: Cancel
Yes: Yes
VerificationKey: Verification key
Verified: Verified
No: No
FullName: Full name
Google: Google
Email: Email
Edit: Edit
Dele: Delete
ConfirmPlease: Please confirm
DeleteAreYouSure: Are you sure you want to delete?
InvalidFormData: Invalid form data
RecordDeleted: Record deleted
NotSpecified: Not specified
RecordEdited: Record edited
SuperuserCannotBeDeleted: Superuser cannot be deleted
Attribution: Attribution
AnotherAccountAccessProhibited: Access to another user's account is prohibited
PersonalInfo: Personal info
Account: Account
Birthday: Birthday
NotIndicated: Not indicated
Initialize: Initialize
UserSession: User session
Database: Database
StoreType: Store type
InvalidStoreType: Invalid store type
ClearSettings: Clear
Cleared: Cleared
GmailAccount: Gmail account
GoogleSecretManager: Google Secret Manager
Generate: Generate
VapidGenerationWarning: Generating a new VAPID key requires all clients to re-subscribe to the push notifications
InvalidGoogleAPITokens: Invalid Google API tokens