GmailAccountNotSet: Le compte Gmail n'est pas défini. Initialisez les jetons.
ThankYou: Merci
ConfirmEmailPlease: Veuillez confirmer votre adresse email en cliquant sur le lien ci-dessous
VerifyYourEmailAddress: Vérifiez votre adresse e-mail
Administrator: Administrateur
Superuser: Superutilisateur
Photo: Photo
DemoUserAccounts: Comptes d'utilisateurs démo
Password: Mot de passe
EmailAddress: Adresse e-mail
CreateAccount: Créer un compte
DoNotHaveAnAccount: Vous n'avez pas de compte ?
SignIn: Se connecter
ForgotYourPassword: Mot de passe oublié?
Or: ou
Back: Retour
ResendEmail: Ré-envoyer l'email
DidNotGetEmail: Vous n'avez pas reçu l'e-mail ?
ClickToVerifyAccount: Cliquez sur le lien dans l'e-mail pour vérifier votre compte
JustSentEmailTo: Nous venons d'envoyer un email à
VerifyEmailPlease: Veuillez vérifier votre email
EmailVerification: Vérification de l'E-mail
CreatePassword: Créer un mot de passe
PasswordRecovery: Récupération de mot de passe
SignInWithGoogle: Connectez-vous avec Google
PageNotFound: Page non trouvée
PermissionDenied: Permission refusée
InvalidArguments: Arguments invalides
BackToHomepage: Retournez à la page d'accueil
InvalidUrlOrRemoved: URL invalide ou ressource supprimée
Authentication: Authentification