Usage: Usage
AuthenticationRequired: Authentification requise
AuthorizationRequired: Autorisation requise
IncomingVideoCallFrom caller: Appel vidéo entrant de #{caller}
IncomingAudioCallFrom caller: Appel audio entrant de #{caller}
CallCanceledByCaller caller: Appel annulé par #{caller}
SendMessagesVideochatOrAudioCall: Envoyez des messages, discutez en vidéo ou passez des appels audio
MyContacts: Mes contacts
YouMightWantToAddAFew: Vous voudrez peut-être en ajouter quelques-uns
YourContactListIsEmpty: Votre liste de contacts est vide
ShowMyContacts: Afficher mes contacts
LogIn: Se connecter
LoginToAccessYourContacts: Connectez-vous pour accéder à vos contacts
WelcomeTo: Bienvenue à
ClientSecret: Secret client
ClientId: Identifiant client
SearchEngineOptimization: Optimisation du moteur de recherche
Username: Nom d'utilisateur
IssueTracking: Signalement de bogues
InterlocutorStartedSession interlocutor: #{interlocutor} a commencé la session
InterlocutorEndedSession interlocutor: #{interlocutor} a terminé la session
EndSession: Terminer la séance
Allow: Permettre
Subscribe: Abonnez-vous
NotNow: Pas maintenant
AllowToBeNotified: Permet d'être averti des appels vidéo entrants, des appels audio et des messages
FailedToCancelSubscription: Échec de l'annulation de l'abonnement
SubscriptionCanceled: Abonnement annulé
SubscriptionFailed: L'abonnement a échoué
SubscriptionSucceeded: L'abonnement a réussi
RemoveAreYouSure: Êtes-vous sûr de vouloir supprimer ?
Remove: Supprimer
CalleeDeclinedTheCall callee: #{callee} a décliné l'appel
CallDeclined: Appel refusé
IncomingAudioCall: Appel audio entrant
IncomingVideoCall: Appel vidéo entrant
Decline: Refuser
Accept: Accepter
MissedCall: Appel manqué
Close: Fermer
VideoSession: Séance vidéo
CallEnded: Appel terminé
IncomingCall: Appel entrant
OutgoingCall: Appel sortant
AudioCall: Appel audio
VideoCall: Appel vidéo
ContactList: Liste de contacts
TextChat: Chat textuel
NewMessage: Nouveau message
Notification: Notification
Ignore: Ignorez
Reply: Répondez
PushNotificationExcception: Erreur de notification push
NoMessagesExchangedYet: Aucun message échangé pour l'instant
SubscribeToNotifications: Abonnez-vous aux notifications
NotGeneratedVAPID: Le VAPID n'a pas été généré
ErDiagram: Diagramme ER
Contact: Contact
Actions: Actions
ViewContact: Voir le contact
NewContactsAdded: Nouveaux contacts ajoutés
AddSelected: Ajouter sélectionnée
AddContacts: Ajouter des contacts
Select: Sélectionner
NoRegisteredUsersYet: Il n'y a pas encore d'utilisateurs enregistrés
Add: Ajouter
NoContactsYet: Il n'y a pas encore de contacts
Message: Message
LoginToViewContacts: Connectez-vous pour voir les contacts
Contacts: Les contacts
GmailAccountNotSet: Le compte Gmail n'est pas défini. Initialisez les jetons.
ThankYou: Merci
ConfirmEmailPlease: Veuillez confirmer votre adresse email en cliquant sur le lien ci-dessous
VerifyYourEmailAddress: Vérifiez votre adresse e-mail
Administrator: Administrateur
Superuser: Superutilisateur
Photo: Photo
DemoUserAccounts: Comptes d'utilisateurs démo
Password: Mot de passe
EmailAddress: Adresse e-mail
CreateAccount: Créer un compte
DoNotHaveAnAccount: Vous n'avez pas de compte ?
SignIn: Se connecter
ForgotYourPassword: Mot de passe oublié?
Or: ou
Back: Retour
ResendEmail: Ré-envoyer l'email
DidNotGetEmail: Vous n'avez pas reçu l'e-mail ?
ClickToVerifyAccount: Cliquez sur le lien dans l'e-mail pour vérifier votre compte
JustSentEmailTo: Nous venons d'envoyer un email à
VerifyEmailPlease: Veuillez vérifier votre email
EmailVerification: Vérification de l'E-mail
CreatePassword: Créer un mot de passe
PasswordRecovery: Récupération de mot de passe
SignInWithGoogle: Connectez-vous avec Google
PageNotFound: Page non trouvée
PermissionDenied: Permission refusée
InvalidArguments: Arguments invalides
BackToHomepage: Retournez à la page d'accueil
InvalidUrlOrRemoved: URL invalide ou ressource supprimée
Authentication: Authentification
AccessDeniedAdminsOnly: Seuls les administrateurs ont accès à cette page. Veuillez vous connecter avec un compte administrateur
LoginPlease: Veuillez vous connecter pour accéder à cette page
Welcome: Bienvenu
Tokens: Jetons
MainMenu: Menu principal
Data: Donnés
Users: Utilisateurs
Documentation: Documentation
SourceCode: Code source
Resources: Ressources
AppDocumentation: Documentation de l'application
NoUsersYet: Il n'y a pas encore d'utilisateurs
SignOut: Se déconnecter
UserAccount: Compte d'utilisateur
User: Utilisateur
Save: Enregistrer
Cancel: Annuler
Yes: Oui
VerificationKey: Clé de vérification
Verified: Vérifié
No: Non
FullName: Nom et prénom
Google: Google
Email: E-mail
Edit: Modifier
Dele: Supprimer
ConfirmPlease: Veuillez confirmer
DeleteAreYouSure: Etes-vous sûr que vous voulez supprimer ?
InvalidFormData: Données de formulaire incorrectes
RecordDeleted: L'enregistrement a été supprimé
NotSpecified: Not specified
RecordEdited: L'enregistrement a été modifié
SuperuserCannotBeDeleted: Le superutilisateur ne peut pas être supprimé
Attribution: Attribution
AnotherAccountAccessProhibited: L'accès au compte d'un autre utilisateur est interdit
PersonalInfo: Données personnelles
Account: Compte
Birthday: Date de naissance
NotIndicated: Non indiqué
Initialize: Initialiser
UserSession: Session utilisateur
Database: Base de données
StoreType: Type de stockage
InvalidStoreType: Type de stockage invalide
ClearSettings: Effacer
Cleared: Effacé
GmailAccount: Compte Gmail
GoogleSecretManager: Google Secret Manager
Generate: Générer
VapidGenerationWarning: La génération d'une nouvelle clé VAPID nécessite que tous les clients se réabonnent aux notifications push.
InvalidGoogleAPITokens: Jetons d'API Google non valides
AppDescription: Application Web progressive pour la messagerie instantanée
AppName: Videre
MetaKeywords: messagerie, instantanée, progressif, web, application, pwa
MetaDescription: Application Web progressive de messagerie instantanée

Doc001 appname href1 href2 href3 href4: L'application <a href=#{href1} target=_blank>#{appname}</a> permet aux utilisateurs d'échanger des messages instantanés via <a href=#{href2} target=_blank>WebSockets</a>, de passer des appels audio et vidéo via <a href=#{href3} target=_blank>WebRTC</a> et d'être avertis via <a href=#{href4} target=_blank>Web Push</a>.

Doc002: Un compte superutilisateur est défini au moment du déploiement. Le superutilisateur gère les autres utilisateurs et accorde ou révoque les privilèges d'administrateur à des utilisateurs spécifiques.

Doc003: Intégration avec des API externes

Doc004 href: <a href=#{href} target=_blank>Le référentiel du projet</a> sur GitHub.

Doc005 href: Veuillez noter que l'application actuellement en cours d'exécution est une application de démonstration. Toutes les actions sont autorisées et encouragées. <a href=#{href} target=_blank>Signalez les bugs</a> sur GitHub.

Doc006 href: Pour s'appeler, les utilisateurs doivent <a href=#{href} target=_blank>s'inscrire</a> dans l'application et s'ajouter à leur liste de contacts parmi les utilisateurs enregistrés.

Doc007: Lors de l'ajout d'un utilisateur à votre liste de contacts, l'application demandera l'autorisation d'envoyer des notifications et de s'abonner au service de notification push.