GmailAccountNotSet: Contul Gmail nu este setat. Inițializați jetoanele.
ThankYou: Vă mulțumim
ConfirmEmailPlease: Vă rugăm să confirmați adresa dvs. de e-mail făcând clic pe link-ul de mai jos
VerifyYourEmailAddress: Verifică-ți adresa de email
Administrator: Administrator
Superuser: Superutilizator
Photo: Foto
DemoUserAccounts: Conturi de utilizator Demo
Password: Parola
EmailAddress: Adresa de e-mail
CreateAccount: Creează-ți un cont
DoNotHaveAnAccount: Nu aveți cont?
SignIn: Conectați-vă
ForgotYourPassword: Ați uitat parola?
Or: sau
Registration: Înregistrare
Back: Înapoi
ResendEmail: Retrimiteți e-mailul
DidNotGetEmail: Nu aţi primit e-mailul?
ClickToVerifyAccount: Faceți clic pe linkul din e-mail pentru a vă verifica contul
JustSentEmailTo: Tocmai am trimis un e-mail la
VerifyEmailPlease: Vă rugăm să vă verificați e-mailul
EmailVerification: Verificare a email-ului
CreatePassword: Creează parolă
PasswordRecovery: Recuperarea parolei
SignInWithGoogle: Conectați-vă cu Google
PageNotFound: Pagina nu a fost găsită
PermissionDenied: Acces refuzat
InvalidArguments: Argumente nevalide
BackToHomepage: Reveniți la pagina de pornire
InvalidUrlOrRemoved: Adresă URL nevalidă sau resursă eliminată
Authentication: Autentificare
AccessDeniedAdminsOnly: Doar administratorii au acces la această pagină. Vă rugăm să vă conectați cu un cont de administrator
LoginPlease: Vă rugăm să vă conectați pentru a accesa această pagină
Welcome: Bine ați venit
Tokens: Jetoane
MainMenu: Meniu principal
Data: Date
Users: Utilizatori
Documentation: Documentație
SourceCode: Codul sursă
Resources: Resurse
AppDocumentation: Documentația aplicației
NoUsersYet: Nu există încă utilizatori
SignOut: Deconectați-vă
UserAccount: Cont de utilizator
User: Utilizator
Save: Salvează
Cancel: Renunță
Yes: Da
VerificationKey: Cheia de verificare
Verified: Verificat
No: Nu
FullName: Numele complet
Google: Google
Email: E-mail
Edit: Editează
Dele: Șterge
ConfirmPlease: Vă rugăm să confirmați
DeleteAreYouSure: Sigur doriți să ștergeți?
InvalidFormData: Date de formular nevalide
RecordDeleted: Înregistrarea a fost ștearsă
NotSpecified: Nespecificat
RecordEdited: Înregistrarea a fost editată
SuperuserCannotBeDeleted: Superutilizatorul nu poate fi șters
Attribution: Atribuire
AnotherAccountAccessProhibited: Accesul la contul altui utilizator este interzis
PersonalInfo: Date personale
Account: Contul
Birthday: Ziua de naștere
NotIndicated: Nu este indicat
Initialize: Inițializează
UserSession: Sesiunea de utilizator
Database: Baza de date
StoreType: Tipul de stocare
InvalidStoreType: Tip de stocare nevalid
ClearSettings: Ștergeți
Cleared: S-a șters
GmailAccount: Cont Gmail
GoogleSecretManager: Google Secret Manager
Generate: Generați
VapidGenerationWarning: Generarea unei noi chei VAPID necesită ca toți clienții să se aboneze din nou la notificările push
InvalidGoogleAPITokens: Jetoane Google API nevalide