WebRealTimeCommunication: Web Real-Time Communication
Configuration: Configurare
Answer: Răspunde
NewMessageFrom user: Mesaj nou de la #{user}
UserIsNowAvailable user: Utilizatorul #{user} este acum disponibil. Puteți suna sau discuta cu el.
RefreshPage: Actualizează pagina
Refresh: Actualizează
EntityCall: Entitatea „Apel”
CallCanceled: Apel anulat
SelectCalleeToCall: Selectați un apelat din listă pentru a apela
YouHaveNotMadeAnyCallsYet: Încă nu ați efectuat niciun apel
Chats: Conversații
Calls: Apeluri
EntityChat: Entitatea „Chat”
PushSubscription: Abonament push
BasicEntities: Entităţile de bază
Overview: Prezentare generală
YouAreNotSubscribedToNotificationsFrom user: Nu sunteți abonat la notificările de la utilizatorul #{user}
UserHasNotAddedYouToHisContactListYet user: #{user} nu v-a adăugat încă la lista lui de contacte
AllowToBeNotifiedBy user: Permiteți utilizatorului #{user} să vă trimită notificări despre apelurile primite
Usage: Utilizare
AuthenticationRequired: Este necesară autentificarea
AuthorizationRequired: Este necesară autorizarea
IncomingVideoCallFrom caller: Apel video primit de la #{caller}
IncomingAudioCallFrom caller: Apel audio primit de la #{caller}
CallCanceledByCaller caller: Apel anulat de #{caller}
SendMessagesVideochatOrAudioCall: Trimiteți mesaje, conversați prin chat video sau faceți apeluri audio
MyContacts: Contactele mele
YouMightWantToAddAFew: Poate doriți să adăugați câteva
YourContactListIsEmpty: Lista dvs. de contacte este goală
ShowMyContacts: Afișează contactele mele
LogIn: Conectează
LoginToAccessYourContacts: Conectați-vă pentru a vă accesa contactele
WelcomeTo: Bun venit la
ClientSecret: Secretul clientului
ClientId: Id-ul clientului
SearchEngineOptimization: Optimizare motor de căutare
Username: Nume de utilizator
IssueTracking: Raportarea erorilor
InterlocutorStartedSession interlocutor: #{interlocutor} a început sesiunea
InterlocutorEndedSession interlocutor: #{interlocutor} a încheiat sesiunea
EndSession: Termină sesiunea
Allow: Permite
Subscribe: Abonați-vă
NotNow: Nu acum
AllowToBeNotified: Permiteți să fiți notificat despre apelurile video, apelurile audio și mesajele primite
FailedToCancelSubscription: Anularea abonamentului a eșuat
SubscriptionCanceled: Abonamentul a fost anulat
SubscriptionFailed: Abonamentul a eșuat
SubscriptionSucceeded: Abonamentul a reușit
RemoveAreYouSure: Sigur doriți să eliminați?
Remove: Eliminați
CalleeDeclinedTheCall callee: #{callee} a refuzat apelul
CallDeclined: Apel refuzat
IncomingAudioCall: Apel audio de intrare
IncomingVideoCall: Apel video de intrare
Decline: Refuzați
Accept: Acceptați
MissedCall: Apel pierdut
Close: Închide
VideoSession: Sesiune video
CallEnded: Apel terminat
IncomingCall: Apel de intrare
OutgoingCall: Apel de ieșire
AudioCall: Apel audio
VideoCall: Apel video
Audio: Audio
Video: Video
ContactList: Listă de contacte
TextChat: Chat prin mesaj text
NewMessage: Mesaj nou
Notification: Notificare
Ignore: Ignorați
Reply: Răspundeți
PushNotificationExcception: Eroare de notificare push
NoMessagesExchangedYet: Niciun mesaj încă schimbat
SubscribeToNotifications: Abonați-vă la notificări
NotGeneratedVAPID: VAPID nu a fost generat
ErDiagram: Diagrama ER
Contact: Contact
Actions: Acțiuni
ViewContact: Vizualizați contactul
NewContactsAdded: Contacte noi adăugate
AddSelected: Adăugați selecționate
AddContacts: Adaugă contacte
Select: Selectează
NoRegisteredUsersYet: Nu există încă utilizatori înregistrați
Add: Adaugă
NoContactsYet: Nu există încă contacte
Message: Mesaj
LoginToViewContacts: Conectați-vă pentru a vizualiza contacte
Contacts: Contacte
GmailAccountNotSet: Contul Gmail nu este setat. Inițializați jetoanele.
ThankYou: Vă mulțumim
ConfirmEmailPlease: Vă rugăm să confirmați adresa dvs. de e-mail făcând clic pe link-ul de mai jos
VerifyYourEmailAddress: Verifică-ți adresa de email
Administrator: Administrator
Superuser: Superutilizator
Photo: Foto
DemoUserAccounts: Conturi de utilizator Demo
Password: Parola
EmailAddress: Adresa de e-mail
CreateAccount: Creează-ți un cont
DoNotHaveAnAccount: Nu aveți cont?
SignIn: Conectați-vă
ForgotYourPassword: Ați uitat parola?
Or: sau
Registration: Înregistrare
Back: Înapoi
ResendEmail: Retrimiteți e-mailul
DidNotGetEmail: Nu aţi primit e-mailul?
ClickToVerifyAccount: Faceți clic pe linkul din e-mail pentru a vă verifica contul
JustSentEmailTo: Tocmai am trimis un e-mail la
VerifyEmailPlease: Vă rugăm să vă verificați e-mailul
EmailVerification: Verificare a email-ului
CreatePassword: Creează parolă
PasswordRecovery: Recuperarea parolei
SignInWithGoogle: Conectați-vă cu Google
PageNotFound: Pagina nu a fost găsită
PermissionDenied: Acces refuzat
InvalidArguments: Argumente nevalide
BackToHomepage: Reveniți la pagina de pornire
InvalidUrlOrRemoved: Adresă URL nevalidă sau resursă eliminată
Authentication: Autentificare
AccessDeniedAdminsOnly: Doar administratorii au acces la această pagină. Vă rugăm să vă conectați cu un cont de administrator
LoginPlease: Vă rugăm să vă conectați pentru a accesa această pagină
Welcome: Bine ați venit
Tokens: Jetoane
MainMenu: Meniu principal
Data: Date
Users: Utilizatori
Documentation: Documentație
SourceCode: Codul sursă
Resources: Resurse
AppDocumentation: Documentația aplicației
NoUsersYet: Nu există încă utilizatori
SignOut: Deconectați-vă
UserAccount: Cont de utilizator
User: Utilizator
Save: Salvează
Cancel: Renunță
Yes: Da
VerificationKey: Cheia de verificare
Verified: Verificat
No: Nu
FullName: Numele complet
Google: Google
Email: E-mail
Edit: Editează
Dele: Șterge
ConfirmPlease: Vă rugăm să confirmați
DeleteAreYouSure: Sigur doriți să ștergeți?
InvalidFormData: Date de formular nevalide
RecordDeleted: Înregistrarea a fost ștearsă
NotSpecified: Nespecificat
RecordEdited: Înregistrarea a fost editată
SuperuserCannotBeDeleted: Superutilizatorul nu poate fi șters
Attribution: Atribuire
AnotherAccountAccessProhibited: Accesul la contul altui utilizator este interzis
PersonalInfo: Date personale
Account: Contul
Birthday: Ziua de naștere
NotIndicated: Nu este indicat
Initialize: Inițializează
UserSession: Sesiunea de utilizator
Database: Baza de date
StoreType: Tipul de stocare
InvalidStoreType: Tip de stocare nevalid
ClearSettings: Ștergeți
Cleared: S-a șters
GmailAccount: Cont Gmail
GoogleSecretManager: Google Secret Manager
Generate: Generați
VapidGenerationWarning: Generarea unei noi chei VAPID necesită ca toți clienții să se aboneze din nou la notificările push
InvalidGoogleAPITokens: Jetoane Google API nevalide
AppDescription: Mesagerie instantanee și apeluri video
AppName: Videre
MetaKeywords: mesagerie, instantanee, progresiv, web, aplicație, pwa
MetaDescription: Aplicație web progresivă pentru mesagerie instantanee și apeluri video

Doc001 appname href1 href2 href3 href4: Aplicația <a href=#{href1} target=_blank>#{appname}</a> permite utilizatorilor să schimbe mesaje instantanee prin <a href=#{href2} target=_blank>WebSockets</a>, să efectueze apeluri audio și video prin <a href=#{href1} target=_blank>WebRTC</a> și să fie notificați prin <a href=#{href4} target=_blank>Web Push</a>.

Doc002: Un cont de superutilizator este definit în momentul implementării. Superutilizatorul gestionează alți utilizatori și acordă sau revocă privilegii de administrator anumitor utilizatori.

Doc003: Integrare cu API-uri externe

Doc004 href: <a href=#{href} target=_blank>Depozitul de proiect</a> pe GitHub.

Doc005 href: Vă rugăm să rețineți că aplicația care rulează în prezent este o aplicație demonstrativă. Orice acțiune este permisă și încurajată. <a href=#{href} target=_blank>Raportați erori</a> pe GitHub.

Doc006 href: Pentru a se suna, utilizatorii trebuie să se <a href=#{href} target=_blank>înregistreze</a> în aplicație și să se adauge reciproc la lista de contacte dintre utilizatorii înregistrați.

Doc007: Când adăugați un utilizator la lista de contacte, aplicația vă va cere permisiunea de a trimite notificări și de a vă abona la serviciul de notificare push.

Doc008: Aplicația folosește serviciul de notificare push al browserului pentru a notifica apelatul cu privire la un apel video sau audio primit.

Doc009 href: La acceptarea apelului, o sesiune video/audio criptată peer-to-peer va începe între apelant și apelat, așa cum este descris de <a href=#{href} target=_blank>protocolul WebRTC</a>.

Doc010 href1 href2: Un utilizator nou se poate <a href=#{href1} target=_blank>înscrie</a> folosind un cont Google existent sau folosind o adresă de e-mail verificată. <a href=#{href2} target=_blank>API-ul Gmail</a> este folosit ca intermediar pentru a trimite linkuri de verificare către căsuța de e-mail a utilizatorului.

Doc011: Un utilizator poate primi rolul de administrator de un superutilizator sau de un alt administrator. Numai utilizatorii cu rol de administrator au acces la datele administrative.

Doc012: Un contact este creat atunci când un utilizator adaugă un alt utilizator la lista de contacte. Dacă fiecare utilizator are unul pe celălalt în lista de contacte, atunci se pot suna.

Doc013: Un abonament push este creat atunci când un utilizator este adăugat la lista de contacte sau poate fi amânat ulterior.

Doc014: Abonamentul poate fi verificat sau reînnoit din elementul de meniu „Vizualizare contact”.

Doc015 href: <a href=#{href} target=_blank>Notificările Web Push</a> sunt folosite pentru a notifica un apelat despre un apel video/audio primit. De asemenea, este folosit pentru a încheia sesiunea video/audio.

Doc016: Entitatea Apel reprezintă apelurile efectuate și primite către utilizator.

Doc017 link: Configurația poate fi furnizată ca o reprezentare textuală a unui obiect JSON, așa cum este descris în <a href=#{link} target=_blank>RTCPeerConnection() constructor</a>.

Doc018: Folosit în principal pentru a specifica serverele STUN și TURN.

Doc019: Entitatea Chat reprezintă mesajele schimbate între doi utilizatori. În mod implicit, mesajele de chat sunt schimbate și stocate folosind protocolul WebSockets. Mesageria peer-to-peer fără stocare intermediară este planificată pentru versiunile viitoare.