GmailAccountNotSet: Аккаунт Gmail не установлен. Инициализируйте токены.
ThankYou: Спасибо
ConfirmEmailPlease: Пожалуйста, подтвердите свой адрес электронной почты, нажав на ссылку ниже
VerifyYourEmailAddress: Проверьте свой адрес электронной почты
Administrator: Администратор
Superuser: Суперпользователь
Photo: Фото
DemoUserAccounts: Демо-аккаунты
Password: Пароль
EmailAddress: Адрес электронной почты
CreateAccount: Зарегистрироваться
DoNotHaveAnAccount: У вас нет учетной записи?
SignIn: Войти
ForgotYourPassword: Забыли пароль?
Or: или
Registration: Регистрация
Back: Вернуться
ResendEmail: Отправить письмо повторно
DidNotGetEmail: Не получили письмо?
ClickToVerifyAccount: Нажмите ссылку в письме, чтобы подтвердить свою учетную запись
JustSentEmailTo: Мы только что отправили электронное письмо на
VerifyEmailPlease: Пожалуйста, подтвердите вашу электронную почту
EmailVerification: Проверка электронной почты
CreatePassword: Создание пароля
PasswordRecovery: Восстановление пароля
SignInWithGoogle: Войти через Google
PageNotFound: Страница не найдена
PermissionDenied: Доступ запрещен
InvalidArguments: Неверные аргументы
BackToHomepage: Вернуться на домашнюю страницу
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация