NoMessagesExchangedYet: Сообщениями пока не обменивались
SubscribeToNotifications: Подписаться на уведомления
NotGeneratedVAPID: VAPID не был создан
ErDiagram: ER-диаграмма
Contact: Контакт
Actions: Действия
ViewContact: Просмотр контакта
NewContactsAdded: Добавлены новые контакты
AddSelected: Добавить выбранные
AddContacts: Добавить контакты
Select: Выбирать
NoRegisteredUsersYet: Зарегистрированных пользователей пока нет
Add: Добавить
NoContactsYet: Контактов пока нет
Message: Сообщение
LoginToViewContacts: Log in to view contacts
Contacts: Контакты
GmailAccountNotSet: Аккаунт Gmail не установлен. Инициализируйте токены.
ThankYou: Спасибо
ConfirmEmailPlease: Пожалуйста, подтвердите свой адрес электронной почты, нажав на ссылку ниже
VerifyYourEmailAddress: Проверьте свой адрес электронной почты
Administrator: Администратор
Superuser: Суперпользователь
Photo: Фото
DemoUserAccounts: Демо-аккаунты
Password: Пароль
EmailAddress: Адрес электронной почты
CreateAccount: Зарегистрироваться
DoNotHaveAnAccount: У вас нет учетной записи?
SignIn: Войти
ForgotYourPassword: Забыли пароль?
Or: или
Registration: Регистрация
Back: Вернуться
ResendEmail: Отправить письмо повторно
DidNotGetEmail: Не получили письмо?
ClickToVerifyAccount: Нажмите ссылку в письме, чтобы подтвердить свою учетную запись
JustSentEmailTo: Мы только что отправили электронное письмо на
VerifyEmailPlease: Пожалуйста, подтвердите вашу электронную почту
EmailVerification: Проверка электронной почты
CreatePassword: Создание пароля
PasswordRecovery: Восстановление пароля
SignInWithGoogle: Войти через Google
PageNotFound: Страница не найдена
PermissionDenied: Доступ запрещен
InvalidArguments: Неверные аргументы
BackToHomepage: Вернуться на домашнюю страницу
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
Welcome: Добро пожаловать
Tokens: Токены
MainMenu: Главное меню
Data: Данные
Users: Пользователи
Documentation: Документация
SourceCode: Исходный код
Resources: Ресурсы
AppDocumentation: Документация приложения
NoUsersYet: Пользователей пока нет
SignOut: Выйти
UserAccount: Учетная запись
User: Пользователь
Save: Сохранить
Cancel: Отмена
Yes: Да
VerificationKey: Ключ проверки
Verified: Проверено
No: Нет
FullName: Полное имя
Google: Google
Email: Электронная почта
Edit: Редактировать
Dele: Удалить
ConfirmPlease: Пожалуйста подтвердите
DeleteAreYouSure: Вы уверены, что хотите удалить?
InvalidFormData: Неверные данные формы
RecordDeleted: Запись удалена
NotSpecified: Не указано
RecordEdited: Запись отредактирована
SuperuserCannotBeDeleted: Суперпользователя нельзя удалить
Attribution: Атрибуция
AnotherAccountAccessProhibited: Доступ к учетной записи другого пользователя запрещен
PersonalInfo: Персональные данные
Account: Учетная запись
Birthday: День рождения
NotIndicated: Не указано
Initialize: Инициализировать
UserSession: Пользовательская сессия
Database: База данных
StoreType: Тип хранилища
InvalidStoreType: Неверный тип хранилища
ClearSettings: Сбросить
Cleared: Очищено
GmailAccount: Учетная запись Gmail
GoogleSecretManager: Google Secret Manager
Generate: Генерировать
VapidGenerationWarning: Для создания нового ключа VAPID всем клиентам необходимо повторно подписаться на push-уведомления
InvalidGoogleAPITokens: Неверные токены Google API
AppDescription: Прогрессивное веб-приложение для обмена мгновенными сообщениями
AppName: Videre
MetaKeywords: мгновенные, сообщения, прогрессивное, веб, приложение, pwa
MetaDescription: Прогрессивное веб-приложение для обмена мгновенными сообщениями