UserIsNowAvailable user: Пользователь #{user} теперь доступен. Вы можете позвонить или пообщаться с ним.
RefreshPage: Обновить страницу
Refresh: Обновить
EntityCall: Сущность «Вызов»
CallCanceled: Вызов отменен
SelectCalleeToCall: Выберите абонента из списка, чтобы позвонить
YouHaveNotMadeAnyCallsYet: Вы еще не совершали ни одного звонка
Chats: Чаты
Calls: Звонки
EntityChat: Сущность "Чат"
PushSubscription: Push-подписка
BasicEntities: Основные сущности
Overview: Обзор
YouAreNotSubscribedToNotificationsFrom user: Вы не подписаны на уведомления от пользователя #{user}
UserHasNotAddedYouToHisContactListYet user: #{user} еще не добавил вас в свой список контактов
AllowToBeNotifiedBy user: Разрешить пользователю #{user} отправлять вам уведомления о входящих звонках
Usage: Применение
AuthenticationRequired: Требуется аутентификация
AuthorizationRequired: Требуется авторизация
IncomingVideoCallFrom caller: Входящий видеозвонок, #{caller}
IncomingAudioCallFrom caller: Входящий аудиовызов, #{caller}
CallCanceledByCaller caller: Вызов отменен, #{caller}
SendMessagesVideochatOrAudioCall: Отправляйте сообщения, общайтесь в видеочате или совершайте аудиозвонки
MyContacts: Мои контакты
YouMightWantToAddAFew: Возможно, вы захотите добавить несколько
YourContactListIsEmpty: Ваш список контактов пуст
ShowMyContacts: Показать мои контакты
LogIn: Войти
LoginToAccessYourContacts: Войдите, чтобы получить доступ к своим контактам
WelcomeTo: Добро пожаловать в
ClientSecret: Секрет клиента
ClientId: Идентификатор клиента
SearchEngineOptimization: Поисковая оптимизация
Username: Имя пользователя
IssueTracking: Отслеживание ошибок
InterlocutorStartedSession interlocutor: #{interlocutor} начал(а) сеанс
InterlocutorEndedSession interlocutor: #{interlocutor} завершил(а) сеанс
EndSession: Завершить сеанс
Allow: Разрешить
Subscribe: Подписаться
NotNow: Не сейчас
AllowToBeNotified: Разрешить получать уведомления о входящих видеозвонках, аудиовызовах и сообщениях
FailedToCancelSubscription: Не удалось отменить подписку
SubscriptionCanceled: Подписка отменена
SubscriptionFailed: Подписка не удалась
SubscriptionSucceeded: Подписка прошла успешно
RemoveAreYouSure: Вы уверены, что хотите удалить?
Remove: Удалить
CalleeDeclinedTheCall callee: #{callee} отклонил(а) звонок
CallDeclined: Вызов отклонен
IncomingAudioCall: Входящий аудиовызов
IncomingVideoCall: Входящий видеозвонок
Decline: Отклонить
Accept: Принять
MissedCall: Пропущенный звонок
Close: Закрыть
VideoSession: Видеосессия
CallEnded: Звонок окончен
IncomingCall: Входящий звонок
OutgoingCall: Исходящий звонок
AudioCall: Аудио звонок
VideoCall: Видеозвонок
Audio: Аудио
Video: Видео
ContactList: Список контактов
TextChat: Чат с помощью текстового сообщения
NewMessage: Новое сообщение
Notification: Уведомление
Ignore: Игнорировать
Reply: Отвечать
PushNotificationExcception: Ошибка push-уведомления
NoMessagesExchangedYet: Сообщениями пока не обменивались
SubscribeToNotifications: Подписаться на уведомления
NotGeneratedVAPID: VAPID не был создан
ErDiagram: ER-диаграмма
Contact: Контакт
Actions: Действия
ViewContact: Просмотр контакта
NewContactsAdded: Добавлены новые контакты
AddSelected: Добавить выбранные
AddContacts: Добавить контакты
Select: Выбирать
NoRegisteredUsersYet: Зарегистрированных пользователей пока нет
Add: Добавить
NoContactsYet: Контактов пока нет
Message: Сообщение
LoginToViewContacts: Войдите для просмотра контактов
Contacts: Контакты
GmailAccountNotSet: Аккаунт Gmail не установлен. Инициализируйте токены.
ThankYou: Спасибо
ConfirmEmailPlease: Пожалуйста, подтвердите свой адрес электронной почты, нажав на ссылку ниже
VerifyYourEmailAddress: Проверьте свой адрес электронной почты
Administrator: Администратор
Superuser: Суперпользователь
Photo: Фото
DemoUserAccounts: Демо-аккаунты
Password: Пароль
EmailAddress: Адрес электронной почты
CreateAccount: Зарегистрироваться
DoNotHaveAnAccount: У вас нет учетной записи?
SignIn: Войти
ForgotYourPassword: Забыли пароль?
Or: или
Registration: Регистрация
Back: Вернуться
ResendEmail: Отправить письмо повторно
DidNotGetEmail: Не получили письмо?
ClickToVerifyAccount: Нажмите ссылку в письме, чтобы подтвердить свою учетную запись
JustSentEmailTo: Мы только что отправили электронное письмо на
VerifyEmailPlease: Пожалуйста, подтвердите вашу электронную почту
EmailVerification: Проверка электронной почты
CreatePassword: Создание пароля
PasswordRecovery: Восстановление пароля
SignInWithGoogle: Войти через Google
PageNotFound: Страница не найдена
PermissionDenied: Доступ запрещен
InvalidArguments: Неверные аргументы
BackToHomepage: Вернуться на домашнюю страницу
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
Welcome: Добро пожаловать
Tokens: Токены
MainMenu: Главное меню
Data: Данные
Users: Пользователи
Documentation: Документация
SourceCode: Исходный код
Resources: Ресурсы
AppDocumentation: Документация приложения
NoUsersYet: Пользователей пока нет
SignOut: Выйти
UserAccount: Учетная запись
User: Пользователь
Save: Сохранить
Cancel: Отмена
Yes: Да
VerificationKey: Ключ проверки
Verified: Проверено
No: Нет
FullName: Полное имя
Google: Google
Email: Электронная почта
Edit: Редактировать
Dele: Удалить
ConfirmPlease: Пожалуйста подтвердите
DeleteAreYouSure: Вы уверены, что хотите удалить?
InvalidFormData: Неверные данные формы
RecordDeleted: Запись удалена
NotSpecified: Не указано
RecordEdited: Запись отредактирована
SuperuserCannotBeDeleted: Суперпользователя нельзя удалить
Attribution: Атрибуция
AnotherAccountAccessProhibited: Доступ к учетной записи другого пользователя запрещен
PersonalInfo: Персональные данные
Account: Учетная запись
Birthday: День рождения
NotIndicated: Не указано
Initialize: Инициализировать
UserSession: Пользовательская сессия
Database: База данных
StoreType: Тип хранилища
InvalidStoreType: Неверный тип хранилища
ClearSettings: Сбросить
Cleared: Очищено
GmailAccount: Учетная запись Gmail
GoogleSecretManager: Google Secret Manager
Generate: Генерировать
VapidGenerationWarning: Для создания нового ключа VAPID всем клиентам необходимо повторно подписаться на push-уведомления
InvalidGoogleAPITokens: Неверные токены Google API
AppDescription: Мгновенные сообщения и видеозвонки
AppName: Videre
MetaKeywords: мгновенные, сообщения, прогрессивное, веб, приложение, pwa
MetaDescription: Прогрессивное веб-приложение для обмена мгновенными сообщениями и видеозвонков

Doc001 appname href1 href2 href3 href4: Приложение <a href=#{href1} target=_blank>#{appname}</a> позволяет пользователям обмениваться мгновенными сообщениями через <a href=#{href2} target=_blank>WebSockets</a>, совершать аудио- и видеозвонки через <a href=#{href3} target=_blank>WebRTC</a> и получать уведомления через <a href=#{href4} target=_blank>Web Push</a>.

Doc002: Учетная запись суперпользователя определяется во время развертывания. Суперпользователь управляет другими пользователями и предоставляет или отзывает права администратора конкретным пользователям.

Doc003: Интеграция с внешними API

Doc004 href: <a href=#{href} target=_blank>Репозиторий проекта</a> на GitHub.

Doc005 href: Обратите внимание, что приложение, работающее в данный момент, является демонстрационным. Любые действия разрешены и поощряются. <a href=#{href} target=_blank>Сообщайте об ошибках</a> на GitHub.

Doc006 href: Чтобы звонить друг другу, пользователям необходимо <a href=#{href} target=_blank>зарегистрироваться</a> в приложении и добавить друг друга в свой список контактов из числа зарегистрированных пользователей.

Doc007: При добавлении пользователя в список контактов приложение запросит разрешение на отправку уведомлений и подписку на службу push-уведомлений.

Doc008: Приложение использует службу push-уведомлений браузера, чтобы уведомить вызываемого абонента о входящем видео- или аудиовызове.

Doc009 href: Приняв вызов, между вызывающим абонентом и вызываемым абонентом начнется одноранговый зашифрованный сеанс видео/аудио, как описано в <a href=#{href} target=_blank>протоколе WebRTC</a>.

Doc010 href1 href2: Новый пользователь может <a href=#{href1} target=_blank>зарегистрироваться</a>, используя существующую учетную запись Google или подтвержденный адрес электронной почты. <a href=#{href2} target=_blank>API Gmail</a> используется в качестве посредника для отправки ссылок проверки в почтовый ящик пользователя.

Doc011: Пользователю может быть предоставлена роль администратора суперпользователем или другим администратором. Только пользователи с ролью администратора имеют доступ к административным данным.

Doc012: Контакт создается, когда пользователь добавляет другого пользователя в свой список контактов. Если у каждого пользователя есть друг друга в списке контактов, они могут звонить друг другу.

Doc013: Push-подписка создается при добавлении пользователя в список контактов или ее можно отложить.

Doc014: Подписку можно проверить или продлить из пункта меню «Просмотреть контакт».

Doc015 href: <a href=#{href} target=_blank>Уведомления Web Push</a> используются для уведомления вызываемого абонента о входящем видео/аудио вызове. Он также используется для завершения видео/аудиосессии.

Doc016: Сущность «Вызов» представляет исходящие и входящие звонки пользователю.